### ISSUE TITLE
Permission to work on Project Euler files.

### ISSUE THREAD

**Issue by Kush1101** [L-ByDo/OneDayOneAlgo#40]
I would like to contribute by adding quality solutions to more problems in Project Euler.

**Comment by maaz-bin-asad** [comment]
@Kush1101 I have assigned it to you

**Comment by Kush1101** [comment]
Thank You for including me in the community. This will be my first project. I will start now

**Comment by maaz-bin-asad** [comment]
All the best

**Comment by Kush1101** [comment]
Will continue to add more solutions. Closing the issue as of now.
