### ISSUE TITLE
Enhance README.md

### ISSUE THREAD

**Issue by Apoorve73** [L-ByDo/OneDayOneAlgo#50]
# Readme needs to be reconstructed for Hacktoberfest 2020.

**Comment by b-farhaan** [comment]
Could you provide me with some details as to what you would like to add in the readme file?
I could start working on it immediately
Do you want me to add the link to Hacktoberfest in the readme file along with some information about the same?

**Comment by Apoorve73** [comment]
Please Go ahead!

**Comment by b-farhaan** [comment]
I have updated the file, please let me know if the pull request was successful
