### ISSUE TITLE
redundant code

### ISSUE THREAD

**Issue by ayaankhan98** [L-ByDo/OneDayOneAlgo#6]
https://github.com/L-ByDo/OneDayOneAlgo/blob/3d25e1ccc338725d64c82f45f01e6daf182bd86b/SieveOfEratosthenes/DamianArado/DamianArado.c#L22

https://github.com/L-ByDo/OneDayOneAlgo/blob/3d25e1ccc338725d64c82f45f01e6daf182bd86b/SieveOfEratosthenes/DamianArado/DamianArado.c#L23

i think using equality operator does not makes any sense in this situation

**Comment by sanjana-302** [comment]
@DamianArado take a look into this and update the file.

**Comment by maaz-bin-asad** [comment]
@DamianArado Why have you put the equality operators.

**Comment by maaz-bin-asad** [comment]
Issue solved. Closing it
