### ISSUE TITLE
Restructure Directories

### ISSUE THREAD

**Issue by Apoorve73** [L-ByDo/OneDayOneAlgo#67]
# Directories need to be restructured using the Best Practices
- [x] Folders to be renamed according to the naming convention wherever necessary.
- [x] Files to be renamed according to naming convention wherever necessary.
- [x] Folders for Languages to be created accordingly, and files to be passed in it. **Eg.** *Cycle_Sort/Python/ should have codes for Cycle Sort using Python only.*

## NOTE: *Check Sorting_Algorithms/Counting_Sort to see the naming convention and directory structure.*

**Comment by souranild** [comment]
i could try this if you could assign to me @Apoorve73 Cheers!

**Comment by Apoorve73** [comment]
Sure thing! Go ahead @sournail :sparkle:

**Comment by souranild** [comment]
in quick sort python for example, there are three versions. 
1. Quick_Sort.py
2. Quick_Sort.ipynb
3. Quick_Sort_Recursion.py

Should i keep all three versions inside the `Python` folder in the above forms?

**Comment by sournail** [comment]
And, Am i supposed to do the naming only for `Algorithms` folder or all the folders? :thinking:

**Comment by Apoorve73** [comment]
Yes Keep All Three, for now!

**Comment by souranild** [comment]
Please check #71 . its fixed @Apoorve73
