### ISSUE TITLE
using varibale size array

### ISSUE THREAD

**Issue by ayaankhan98** [L-ByDo/OneDayOneAlgo#7]
https://github.com/L-ByDo/OneDayOneAlgo/blob/3d25e1ccc338725d64c82f45f01e6daf182bd86b/SieveOfEratosthenes/DamianArado/DamianArado.c#L12

some compilers like clang would not permite to compile the program and will through an error
```
error: variable-sized object may not be initialized
        int array[limit]={0};
                  ^~~~~
1 error generated.
```
it is better to use the constant size with C-Style arrays or the another possible solution is to dynamically allocate the array

**Comment by maaz-bin-asad** [comment]
@DamianArado 
Assuming you have C99 compiler, it's not allowed to use variable size arrays. Instead, give a constant value to reference variable "limit"
