### ISSUE TITLE
[ADD] Solutions of famous questions from CSES

### ISSUE THREAD

**Issue by Apoorve73** [L-ByDo/OneDayOneAlgo#94]
Add solution to questions from https://cses.fi/problemset/

- Make the directory in the given format
- CSES_solution / [NAME OF PROBLEM] / [SOLUTION FILE]
- CSES_solution / [NAME OF PROBLEM] / [README]

**Note:** README for every problem involves the link to problem and short description of approach.

**Comment by salonigupta1** [comment]
Can I work on this issue?

**Comment by maaz-bin-asad** [comment]
@salonigupta1 Assigning issue to you .
